### ISSUE TITLE
Install older versions of plugin not possible

### ISSUE THREAD

**Issue by VDRainer** [hacs/frontend#20]
## Version of HACS
0.17.1

## Describe the bug
On selecting an older version of a plugin, the spinner runs forever and it's not possible to install.
Sometimes the button to reinstall shows up, sometimes not.
The only way to stop the spinner is to restart HA.
![20191118_13:20:10_001](https://user-images.githubusercontent.com/26381449/69052270-ecf85280-0a06-11ea-8d97-aa856e4d1579.png)

## Debug log

A lot of TypeErrors in the browser console:
```text

TypeError: this.status is undefined
main.js:628:198
TypeError: this.status is undefined
main.js:636:709
TypeError: this.status is undefined
main.js:628:198

```

**Comment by ludeeus** [comment]
Fixed in 0.17.2

**Comment by VDRainer** [comment]
Sorry @ludeeus , still no luck to downgrade a plugin.
Console error
```
uncaught exception: Object
```
and spinner runs forever. :stuck_out_tongue_winking_eye:

**Comment by ludeeus** [comment]
Expand that object

**Comment by VDRainer** [comment]
Thanks for reopening.
How do i expand it?
That's all i see.
![Auswahl_221](https://user-images.githubusercontent.com/26381449/69092022-d0cad480-0a4b-11ea-996f-b2f4f49d1dc2.png)

**Comment by ludeeus** [comment]
I don't know, get a better browser?`
chrome, for instance, _cough cough_ 😂

**Comment by VDRainer** [comment]
F..k! Looks like i can downgrade in Chrome and no error in the console, but now i can't upgrade to the latest version, (Mini-Media-Player) btw.
Restarted HA, but still no luck to update to the latest version.
Settings -> Upgrade all, did i at the end.
Somethings going on.
Need to give up for now. That spinner hypnotized me. :flushed:

**Comment by VDRainer** [comment]
Definitely a Firefox issue.

I opened the same plugin (button-card this time) in FF and Chrome.

Selecting another version in Chrome, everything works.
```
2019-11-19 09:37:10 INFO (MainThread) [hacs] Running set_state for custom-cards/button-card
2019-11-19 09:37:10 DEBUG (MainThread) [hacs.data] Saving data
2019-11-19 09:37:10 INFO (MainThread) [hacs] Running set_version for custom-cards/button-card
2019-11-19 09:37:14 DEBUG (MainThread) [hacs.data] Saving data
```
Selecting another version in Firefox, the spinner shows, also in chrome.
```
2019-11-19 09:37:45 INFO (MainThread) [hacs] Running set_state for custom-cards/button-card
2019-11-19 09:37:45 DEBUG (MainThread) [hacs.data] Saving data
```
Selecting another version in Chrome, spinner stops, also in Firefox.
```
2019-11-19 09:38:36 INFO (MainThread) [hacs] Running set_state for custom-cards/button-card
2019-11-19 09:38:36 DEBUG (MainThread) [hacs.data] Saving data
2019-11-19 09:38:36 INFO (MainThread) [hacs] Running set_version for custom-cards/button-card
2019-11-19 09:38:40 DEBUG (MainThread) [hacs.data] Saving data
```
:flushed:
Hope that helps to find the issue.

**Comment by ludeeus** [comment]
Sooo... Just use chrome? 🤣

**Comment by VDRainer** [comment]
But only for card up/downgrades. :grin:

**Comment by ludeeus** [comment]
Fixed in 0.17.4

**Comment by VDRainer** [comment]
Thanks so much!
